### ISSUE TITLE
500-shade as the middle point for each color

### ISSUE THREAD

**Issue by macCesar** [tombohub/palettolithic#2]
Hi tombohub.. Bootstrap defines the 500 shade as the middle point for each color.

https://getbootstrap.com/docs/5.0/customize/color/

For example: the `primary` color is equal to `blue-500` or `danger` is equal to `red-500`.

Can your generator be adapted to set the 500 shade as the base for each generated color ??

Thanks!!!

**Comment by tombohub** [comment]
Thank you, so they changed from 600 to 500? 

Yeah, seems like my palette is lighter then theirs. Ok I'll see what I can do, just give me some time. Their shades are custom picked for each color so there will always be a difference between code generated and their colors.

I'll see what I can do.

Thank you for using my tool, please share

**Comment by tombohub** [comment]
@macCesar 
I have adjusted to bootstrap 5.0. Check it out. 

Are you using Tailwindcss too?

**Comment by macCesar** [comment]
Thanks man... I'll check it out..

Yes, I'm also using tailwindcss.

**Comment by tombohub** [comment]
does it generate good code for tailwindcss too?

I didn't use tailwind in a while, I know they upgraded
